<a href="https://colab.research.google.com/github/datacode-tr/Statistics/blob/main/Statistics_Assignment_2_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [ ]:
import numpy as np
import pandas as pd
import scipy as sp
from scipy.stats import mode


 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
samples = np.random.normal(loc=100, scale=15, size=100)
samples

array([ 90.0424938 ,  87.9343603 ,  94.58804594,  70.78146448,
       105.80766279,  95.2812898 ,  84.99115948,  99.9739299 ,
        89.13564983,  53.20929644,  89.71530395, 105.22409269,
        89.490969  , 100.11900037,  69.90755648,  97.10936441,
       125.16157535, 109.75811748, 100.90799657,  84.91572798,
       112.29498376, 117.56321739, 130.25957655,  84.96964367,
       114.095244  ,  94.9319734 , 102.16650005, 107.52991208,
       111.79916388,  84.34788113, 105.83786672, 104.33103109,
       122.35681651,  99.0519872 , 117.96020584, 119.3054236 ,
       101.33022899,  96.79408271,  92.75693668,  95.36448292,
       103.98008356, 109.9609254 , 126.91339008, 100.79833922,
        88.69009794,  98.96059739,  77.41216791,  81.91281509,
        90.88030914, 118.97197706,  85.46570321, 101.714014  ,
        76.93774605,  84.13314137,  81.40164205, 123.60514707,
       120.14647225,  77.40230827, 105.05751174, 106.56492018,
        95.13207429, 104.3397172 , 105.48475363,  89.71

Compute the **mean**, **median**, and **mode**

In [ ]:
mean =np.mean(samples)
print('The mean of samples is :', mean)
median =np.median(samples)
print('The median of samples is', median)
std_samples= np.std(samples)
print('The Std of samples is', std_samples)
mode =sp.stats.mode(samples)
print('The mode of samples is :' , mode)

The mean of samples is : 100.05419220224083
The median of samples is 100.68947218119786
The Std of samples is 14.661799189558568
The mode of samples is : ModeResult(mode=array([53.20929644]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:

min = np.min(samples)
print('the min of samples is', min)
max = np.max(samples)
print('the max of samples is', max)
q1 =np.quantile(samples, 0.25)
print('the q1 of samples is', q1)
q3 =np.quantile(samples, 0.75)
print('the q3 of samples is', q3)
iqr = q3-q1
print('the iqr of samples is', iqr)

the min of samples is 53.209296437220125
the max of samples is 147.5044356559605
the q1 of samples is 89.9611955031788
the q3 of samples is 107.96241685073022
the iqr of samples is 18.00122134755142


Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
print('The variance of samples is ', variance)
std_dev =np.std(samples)
print('the standart deviation of samles is ', std_dev)

The variance of samples is  214.9683554749403
the standart deviation of samles is  14.661799189558568


Compute the **skewness** and **kurtosis**

In [ ]:
skewness = sp.stats.skew(samples)
print('the skewnes of samples is ', skewness)
kurtosis =sp.stats.kurtosis(samples)
print('the kurtosis of samples is ', kurtosis)

the skewnes of samples is  -0.0516523477199986
the kurtosis of samples is  0.8396813261905622


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
sayılar=[3,2,1,7,8,9,4,5,6,11]
y = np.array(sayılar)
y

array([ 3,  2,  1,  7,  8,  9,  4,  5,  6, 11])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.64139426],
       [0.64139426, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
x
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
Data_Frame=pd.DataFrame([x,y])
r =Data_Frame.corr(method='pearson')
r

0    1    2    3    4    5    6    7    8    9
0  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
5  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
6 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
7 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
8 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
9 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho =Data_Frame.corr(method='spearman')
rho

0    1    2    3    4    5    6    7    8    9
0  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
5  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
6 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
7 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
8 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
9 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
tips.corr(method='pearson')

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000